'use strict';
// Independent end-to-end checks. Only isolated temporary sources/catalogs are written.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process'),crypto=require('node:crypto');
let pw;try{pw=require(process.env.PLAYWRIGHT_MODULE||'playwright');}catch{pw=require('C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');}
const python=process.env.PYTHON||'C:/Python314/python.exe',chromium=process.env.CHROMIUM_EXECUTABLE||'C:/Users/user/AppData/Local/ms-playwright/chromium-1187/chrome-win/chrome.exe';
const evidence=process.env.GILES_WORKFLOW_EVIDENCE||null;
(async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'giles-workflows-')),a=path.join(root,'alpha'),b=path.join(root,'beta'),archive=path.join(root,'archive'),catalog=path.join(root,'catalog.json');
 for(const p of [a,b,archive,path.join(a,'notes'),path.join(a,'docs'),path.join(a,'v1.0'),path.join(b,'notes')])fs.mkdirSync(p,{recursive:true});
 const quote='  Exact source — café 世界 💠‍🌐.\nKeep `literal` and ``` code fences.\n',second='Second source: the corrected condition applies only after review.\n',index='# Actual source index\nThis is source content, not the catalog description.\n[Plain note](notes/first.md)\n[Research PDF](<docs/Page set.pdf>)\n[Encoded source](notes/first.md)\n',long='Beginning\n'+('café 世界💠 ' .repeat(6500))+'\nFINAL SOURCE EVIDENCE';
 const sourceOne=quote+'Unselected neighboring source text.\n',sourceTwo=second+'Unselected neighboring source text.\n';fs.writeFileSync(path.join(a,'INDEX.md'),index);fs.writeFileSync(path.join(a,'notes','first.md'),sourceOne);fs.writeFileSync(path.join(b,'INDEX.md'),'Second source index.\n');fs.writeFileSync(path.join(b,'notes','second.md'),sourceTwo);fs.writeFileSync(path.join(a,'long.md'),long);fs.writeFileSync(path.join(a,'v1.0','README.md'),'Dotted directory contains real contents.\n');
 const crlfPassage='  CRLF source — café 世界 💠.\r\nSecond original line.\r\n',crlfSource=crlfPassage+'Unselected neighboring text.\r\n';fs.writeFileSync(path.join(a,'crlf.md'),crlfSource);
 fs.writeFileSync(path.join(a,'image.png'),Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j5N0AAAAASUVORK5CYII=','base64'));
 cp.execFileSync(python,['-B','-X','utf8','-c',String.raw`
import pathlib,sys,sqlite3,zipfile
from pypdf import PdfWriter
from pypdf.generic import DictionaryObject,NameObject,DecodedStreamObject
root=pathlib.Path(sys.argv[1]);a=root/'alpha';archive=root/'archive';(archive/'rag').mkdir()
w=PdfWriter()
for n in range(1,9):
 p=w.add_blank_page(width=612,height=792);font=DictionaryObject({NameObject('/Type'):NameObject('/Font'),NameObject('/Subtype'):NameObject('/Type1'),NameObject('/BaseFont'):NameObject('/Helvetica')});p[NameObject('/Resources')]=DictionaryObject({NameObject('/Font'):DictionaryObject({NameObject('/F1'):font})});s=DecodedStreamObject();s.set_data(f'BT /F1 12 Tf 40 700 Td (Real PDF page {n}: source evidence.) Tj ET'.encode());p[NameObject('/Contents')]=w._add_object(s)
with (a/'docs/Page set.pdf').open('wb') as f:w.write(f)
xml='<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t>DOCX actual café 世界.</w:t></w:r></w:p><w:p><w:r><w:t>Second paragraph and original condition.</w:t></w:r></w:p></w:body></w:document>'
with zipfile.ZipFile(a/'source.docx','w') as z:z.writestr('word/document.xml',xml)
con=sqlite3.connect(archive/'rag/archive-current.sqlite3');con.executescript("CREATE TABLE documents(id INTEGER PRIMARY KEY,source TEXT,external_id TEXT,title TEXT,created_at TEXT,source_path TEXT,metadata_json TEXT,ingested_at TEXT);CREATE TABLE chunks(id INTEGER PRIMARY KEY,document_id INTEGER,ordinal INTEGER,role TEXT,created_at TEXT,content TEXT);CREATE VIRTUAL TABLE chunks_fts USING fts5(content,content='chunks',content_rowid='id');")
con.execute('INSERT INTO documents VALUES (?,?,?,?,?,?,?,?)',(1,'codex','stable-conversation','Recorded discussion','2026-01-01','raw/original.jsonl','{}','2026-01-02'))
for n,role,body in [(0,'user','Question about the special evidence condition.'),(1,'assistant','Archive source evidence café 世界 💠. '+('continued source context '*1800)),(2,'user','Correction: the condition applies after review.')]:
 con.execute('INSERT INTO chunks VALUES (?,?,?,?,?,?)',(n+1,1,n,role,'2026-01-01',body));con.execute('INSERT INTO chunks_fts(rowid,content) VALUES (?,?)',(n+1,body))
con.commit();con.close();(archive/'README.md').write_text('An archive owner index.\n',encoding='utf-8')
`,root],{stdio:'pipe'});
 const stores=[{id:'alpha',name:'A Laboratory Archive',location:a,entrypoint:'INDEX.md',summary:'Catalog description must stay separate.',topics:['research','shared'],role:'canonical',owner:'Fixture owner',inspection:'metadata_only',sections:[{id:'first',title:'First evidence',path:'notes/first.md'},{id:'long',title:'Long source',path:'long.md'},{id:'pdf',title:'PDF pages',path:'docs/Page set.pdf'},{id:'docx',title:'Word source',path:'source.docx'},{id:'image',title:'Source picture',path:'image.png'},{id:'dotted',title:'Version folder',path:'v1.0'},{id:'crlf',title:'Windows source',path:'crlf.md'}]},{id:'beta',name:'B Second Archive',location:b,entrypoint:'INDEX.md',topics:['shared'],role:'derivative',sections:[{id:'second',title:'Second evidence',path:'notes/second.md'}]},{id:'archive',name:'C Personal AI Archive',location:archive,entrypoint:'README.md',topics:['conversations'],sections:[{id:'rag',title:'Published conversations',path:'rag'}]}];
 fs.writeFileSync(catalog,JSON.stringify({schema:'giles-knowledge-catalog/v1',revision:0,stores}));const catalogBefore=fs.readFileSync(catalog);
 function treeHashes(){const out={};for(const base of [a,b,archive]){const visit=p=>{for(const x of fs.readdirSync(p,{withFileTypes:true})){const full=path.join(p,x.name);if(x.isDirectory())visit(full);else out[path.relative(root,full)]=crypto.createHash('sha256').update(fs.readFileSync(full)).digest('hex');}};visit(base);}return out;}let expectedSources=treeHashes();
 const server=cp.spawn(python,['-B','-X','utf8',path.resolve(__dirname,'../scripts/giles.py'),'--catalog',catalog,'serve','--port','0','--no-browser']);let browser,stderr='',passed=0;const failures=[],errors=[],consoleErrors=[],requests=[];server.stderr.on('data',d=>stderr+=d.toString());
 try{
  const url=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Server did not start: '+stderr)),10000);server.stdout.on('data',d=>{const m=d.toString().match(/http:\/\/127\.0\.0\.1:\d+\//);if(m){clearTimeout(timer);resolve(m[0]);}});server.on('error',reject);server.on('exit',c=>reject(Error('Server exited '+c+': '+stderr)));});
  browser=await pw.chromium.launch({headless:true,executablePath:chromium});const ctx=await browser.newContext({permissions:['clipboard-read','clipboard-write'],viewport:{width:1440,height:1000},reducedMotion:'reduce'}),page=await ctx.newPage();page.setDefaultTimeout(6000);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});page.on('request',r=>requests.push({url:r.url(),method:r.method()}));
  const get=async p=>{const r=await ctx.request.get(url+p);assert.equal(r.status(),200,await r.text());return r.json();};const work=()=>get('api/workbench');
  const check=async(name,fn)=>{try{await fn();passed++;console.log('PASS '+name);}catch(e){failures.push({name,error:e.stack});console.log('FAIL '+name+' :: '+e.message);}};
  const settle=()=>page.waitForFunction(()=>!!document.querySelector('#source-view')&&!document.querySelector('#source-view .loading'));
  const choose=async id=>{await page.locator(`[data-id="${id}"]`).click();await settle();};
  const section=async(id,kind='text')=>{await page.locator(`[data-section="${id}"]`).click();if(kind==='image')await page.locator('.source-image').waitFor();else if(kind==='folder')await page.locator('#source-view .source-list').waitFor();else await page.locator('#source-view .sample').waitFor();await settle();};
  const selectText=async text=>{await page.locator('#source-view .sample').evaluate((pre,value)=>{const node=pre.firstChild,start=node.textContent.indexOf(value);if(start<0)throw Error('Expected passage absent from reader');const range=document.createRange();range.setStart(node,start);range.setEnd(node,start+value.length);const selection=getSelection();selection.removeAllRanges();selection.addRange(range);pre.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}));},text);};
  const collect=async text=>{const n=(await work()).excerpts.length;if(text!==null)await selectText(text);await page.locator('#collect-selection').click();await page.waitForFunction(n=>document.querySelectorAll('.working-excerpt').length===n+1,n);return(await work()).excerpts.at(-1);};
  await page.goto(url);await page.locator('#stores [data-id=alpha]').waitFor();await page.waitForFunction(()=>document.querySelector('#work-title')?.value==='Knowledge work');await settle();
  await check('automatic overview delivers actual index and preserves catalog inspection claim',async()=>{assert.equal(await page.locator('#source-view .sample').textContent(),index);assert.match(await page.locator('.description-basis').textContent(),/metadata only/);assert.equal((await get('api/catalog')).stores[0].inspection,'metadata_only');});
  await check('shared-topic map edges name the actual recorded basis',async()=>{assert.equal(await page.locator('#estate-map path[data-to=beta]').getAttribute('data-topics'),'shared');assert.equal(await page.locator('#estate-map path[data-to=archive]').count(),0);});
  await section('first');await check('named section reads exact source bytes with visible breadcrumbs',async()=>{assert.equal(await page.locator('#source-view .sample').textContent(),sourceOne);assert.equal(await page.locator('#breadcrumbs [data-crumb="notes/first.md"]').textContent(),'first.md');});
  let first=await collect(quote);await check('collected passage preserves exact whitespace, Unicode, source route and verified status',async()=>{assert.equal(first.text,quote);assert.equal(first.path,'notes/first.md');assert.equal(first.store_id,'alpha');assert.equal(first.location,a);assert.equal(first.verification.status,'verified_match');assert.equal(first.provenance.owner,'Fixture owner');});
  await check('plain text provenance never claims a nonexistent PDF page',async()=>{assert.ok(!/\bpage\s*1\b/i.test(await page.locator(`[data-excerpt="${first.id}"] .anchor`).textContent()));});
  const note='My interpretation: retain the condition.\nThis annotation is separate — 世界 💠.';
  await page.locator(`[data-note="${first.id}"]`).fill(note);await page.locator('#work-title').fill('Evidence packet 世界');await page.locator('#work-goal').fill('Compare the original with the corrected condition.');const saved=page.waitForResponse(r=>r.url().includes('/api/workbench/save'));await page.locator('#save-work').click();assert.equal((await saved).status(),200);
  await page.reload();await page.locator('[data-note]').waitFor();await settle();await check('task and separate annotations persist through actual reload',async()=>{const w=await work();assert.equal(w.title,'Evidence packet 世界');assert.equal(w.goal,'Compare the original with the corrected condition.');assert.equal(w.excerpts[0].note,note);assert.equal(w.excerpts[0].text,quote);assert.ok(fs.existsSync(path.join(root,'workbench.json')));});
  await choose('beta');await section('second');const other=await collect(second);await page.locator(`[data-compare="${first.id}"]`).check();await page.locator(`[data-compare="${other.id}"]`).check();await page.locator('#compare-work').click();await check('comparison shows the chosen original snapshots without manufacturing synthesis',async()=>{assert.deepEqual(await page.locator('#comparison .compare-columns pre').allTextContents(),[quote,second]);assert.match(await page.locator('#comparison').textContent(),/no claim of semantic agreement/);});
  await page.locator('#compile-work').click();await page.locator('#packet-view pre').waitFor();let packet=await page.locator('#packet-view pre').textContent();await check('compiled packet contains real excerpts, task, source provenance and distinct annotation',async()=>{for(const v of [quote,second,note,'Compare the original with the corrected condition.',a+'/notes/first.md',b+'/notes/second.md','User annotation (not source text)','no semantic synthesis'])assert.ok(packet.includes(v),'Missing packet content: '+v);assert.ok(packet.indexOf(quote)<packet.indexOf(note));assert.ok(packet.includes('````\n'+quote+'\n````'),'Literal source code fences must survive assembly');});
  const dl=page.waitForEvent('download');await page.locator('#download-packet').click();const packetDL=await dl;await check('Markdown download bytes equal rendered source-bearing packet',async()=>{assert.equal(fs.readFileSync(await packetDL.path(),'utf8'),packet);});
  const ex=page.waitForEvent('download');await page.locator('#export-work').click();const exported=await ex;const historical=JSON.parse(fs.readFileSync(await exported.path(),'utf8'));await check('working-tray export includes actual retained quotations and annotations',async()=>{assert.equal(historical.excerpts[0].text,quote);assert.equal(historical.excerpts[0].note,note);assert.equal(historical.excerpts[1].text,second);});
  await page.locator(`[data-remove-excerpt="${other.id}"]`).click();await page.waitForFunction(()=>document.querySelectorAll('.working-excerpt').length===1);await page.locator('#work-file').setInputFiles({name:'historical.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(historical))});await page.waitForFunction(()=>document.querySelectorAll('.working-excerpt').length===2);await check('tray import restores exact historical data and checks source agreement',async()=>{const w=await work();for(let i=0;i<2;i++){assert.equal(w.excerpts[i].text,historical.excerpts[i].text);assert.equal(w.excerpts[i].note,historical.excerpts[i].note);assert.equal(w.excerpts[i].verification.status,'verified_match');}});
  await choose('alpha');await section('long');let assembled='';let chunks=0;for(;;){assembled+=await page.locator('#source-view .sample').textContent();chunks++;if(!await page.locator('#reader-next').count())break;await page.locator('#reader-next').click();await page.locator('#source-view .sample').waitFor();await settle();if(chunks>12)throw Error('Pagination failed to advance');}await check('reader reaches complete long Unicode source without skipped bytes or replacement glyphs',async()=>{assert.ok(chunks>2);assert.equal(assembled,long);assert.ok(!assembled.includes('\uFFFD'));});
  await page.locator('#reader-first').click();await page.locator('#source-view .sample').waitFor();await check('start-of-document control returns to first source bytes',async()=>{assert.ok((await page.locator('#source-view .sample').textContent()).startsWith('Beginning\n'));});
  await section('crlf');await check('Windows source reader preserves original CRLF contents in the DOM',async()=>{assert.equal(await page.locator('#source-view .sample').textContent(),crlfSource);});const crlfItem=await collect(crlfPassage);await check('Windows CRLF selection remains verbatim through collection, persistence and packet assembly',async()=>{assert.equal(crlfItem.text,crlfPassage);assert.equal((await work()).excerpts.find(x=>x.id===crlfItem.id).text,crlfPassage);assert.ok((await get('api/packet')).markdown.includes(crlfPassage));});
  await section('docx');await check('DOCX control delivers actual paragraph text rather than file metadata',async()=>{assert.equal(await page.locator('#source-view .sample').textContent(),'DOCX actual café 世界.\nSecond paragraph and original condition.');});
  await section('pdf');let pdfFirst=await page.locator('#source-view .sample').textContent();await page.locator('#reader-next').click();await page.locator('#source-view .sample').waitFor();await check('PDF reader delivers real page windows and advances to pages seven and eight',async()=>{assert.ok(pdfFirst.includes('Real PDF page 1'));assert.ok(pdfFirst.includes('Real PDF page 6'));assert.ok(!pdfFirst.includes('Real PDF page 7'));const last=await page.locator('#source-view .sample').textContent();assert.ok(last.includes('Real PDF page 7'));assert.ok(last.includes('Real PDF page 8'));assert.ok(!last.includes('Real PDF page 1'));assert.match(await page.locator('.pagination').textContent(),/7–8 of 8/);});
  const pdfItem=await collect('Real PDF page 8: source evidence.');await check('collected PDF evidence retains its true page window anchor',async()=>{const x=(await work()).excerpts.at(-1);assert.equal(x.format,'pdf');assert.equal(x.anchor.page,6);assert.equal(x.text,'Real PDF page 8: source evidence.');});
  await check('PDF provenance labels its extraction window rather than assigning the excerpt a false page',async()=>{const label=await page.locator(`[data-excerpt="${pdfItem.id}"] .anchor`).textContent();assert.match(label,/PDF window starts (?:at )?page 7/i);assert.match(pdfItem.limits.join(' '),/pages 7–8 of 8/);});
  await section('image','image');await page.waitForFunction(()=>document.querySelector('.source-image')?.complete);await check('image reader delivers actual decoded image pixels',async()=>{assert.equal(await page.locator('.source-image').evaluate(x=>x.naturalWidth),1);});const imageItem=await collect(null);await check('image collection preserves reference and never invents OCR',async()=>{assert.equal(imageItem.format,'image');assert.equal(imageItem.text,'');assert.match(imageItem.limits.join(' '),/no OCR/);});
  await section('dotted','folder').catch(()=>{});await page.locator('[data-path="v1.0/README.md"]').click();await page.locator('#source-view .sample').waitFor();await check('dotted folder and direct file controls execute correct filesystem semantics',async()=>{assert.equal(await page.locator('#source-view .sample').textContent(),'Dotted directory contains real contents.\n');});
  await page.locator('[data-section=""]').click();await settle();await page.locator('.index-preview [data-path="INDEX.md"]').click();await page.locator('#source-view .sample').waitFor();await check('Markdown link with angle brackets and spaces opens the actual linked PDF',async()=>{await page.getByRole('button',{name:'Research PDF ↗',exact:true}).click();await settle();assert.ok((await page.locator('#source-view .sample').textContent()).includes('Real PDF page 1'));assert.match(await page.locator('#breadcrumbs').textContent(),/Page set\.pdf/);});
  await choose('alpha');let release,seen,finished;const held=new Promise(r=>release=r),started=new Promise(r=>seen=r),completed=new Promise(r=>finished=r);const hold=async r=>{const response=await r.fetch();seen();await held;await r.fulfill({response});finished();};await page.route('**/api/preview?*',hold);await page.locator('[data-section=first]').click();await started;await choose('beta');const responseDone=page.waitForResponse(r=>r.url().includes('/api/preview?'));release();await completed;await(await responseDone).finished();await page.unroute('**/api/preview?*',hold);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await check('delayed source read cannot fill a different collection',async()=>{assert.equal(await page.locator('#detail h2').textContent(),'B Second Archive');assert.equal(await page.locator('#source-view .sample').textContent(),'Second source index.\n');});
  await choose('archive');await page.waitForFunction(()=>document.querySelectorAll('#archive-results [data-record]').length===3);await check('archive overview immediately delivers recent real published message excerpts',async()=>{const recent=await page.locator('#archive-results').textContent();for(const text of ['Question about the special evidence condition.','Archive source evidence','Correction: the condition applies after review.'])assert.ok(recent.includes(text));assert.match(await page.locator('.archive-reader .provenance').first().textContent(),/published/);});
  await page.locator('[data-section=rag]').click();await page.waitForFunction(()=>document.querySelectorAll('#archive-results [data-record]').length===3);await check('named archive section exposes native retrieval with actual published content',async()=>{assert.equal(await page.locator('#breadcrumbs [data-crumb=rag]').textContent(),'rag');assert.ok((await page.locator('#archive-results').textContent()).includes('Archive source evidence'));assert.equal(await page.locator('#source-view .source-state.error').count(),0);});
  await page.locator('[data-path="rag/archive-current.sqlite3"]').click();await page.waitForFunction(()=>document.querySelectorAll('#archive-results [data-record]').length===3);await check('direct archive database path exposes native retrieval instead of unsupported binary',async()=>{assert.equal(await page.locator('#breadcrumbs [data-crumb="rag/archive-current.sqlite3"]').textContent(),'archive-current.sqlite3');assert.ok((await page.locator('#archive-results').textContent()).includes('Correction: the condition applies after review.'));assert.equal(await page.locator('#source-view .source-state.error').count(),0);});
  let releaseRecent,seenRecent,finishedRecent;const recentHeld=new Promise(r=>releaseRecent=r),recentStarted=new Promise(r=>seenRecent=r),recentCompleted=new Promise(r=>finishedRecent=r);const holdRecent=async route=>{const u=new URL(route.request().url());if(u.searchParams.get('q')!==''){await route.continue();return;}const response=await route.fetch();seenRecent();await recentHeld;await route.fulfill({response});finishedRecent();};await page.route('**/api/archive/search?*',holdRecent);await page.locator('[data-section=rag]').click();await recentStarted;const explicitResponse=page.waitForResponse(r=>{const u=new URL(r.url());return u.pathname==='/api/archive/search'&&u.searchParams.get('q')==='archive source evidence';});await page.locator('#archive-query').fill('archive source evidence');await page.locator('#archive-find').click();assert.equal((await explicitResponse).status(),200);await page.waitForFunction(()=>document.querySelectorAll('#archive-results [data-record]').length===1&&document.querySelector('#archive-results').textContent.includes('Archive source evidence'));const automaticResponse=page.waitForResponse(r=>{const u=new URL(r.url());return u.pathname==='/api/archive/search'&&u.searchParams.get('q')==='';});releaseRecent();await recentCompleted;await(await automaticResponse).finished();await page.unroute('**/api/archive/search?*',holdRecent);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await check('delayed automatic recent results cannot overwrite the later explicit archive query',async()=>{assert.equal(await page.locator('#archive-query').inputValue(),'archive source evidence');assert.equal(await page.locator('#archive-results [data-record]').count(),1);assert.ok((await page.locator('#archive-results').textContent()).includes('Archive source evidence'));assert.ok(!(await page.locator('#archive-results').textContent()).includes('Question about the special evidence condition.'));});
  const found=page.waitForResponse(r=>{const u=new URL(r.url());return u.pathname==='/api/archive/search'&&u.searchParams.get('q')==='archive source evidence';});await page.locator('#archive-query').fill('archive source evidence');await page.locator('#archive-find').click();assert.equal((await found).status(),200);await page.waitForFunction(()=>document.querySelectorAll('#archive-results [data-record]').length===1&&document.querySelector('#archive-results').textContent.includes('Archive source evidence'));if(evidence){fs.mkdirSync(evidence,{recursive:true});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(evidence,'archive-retrieval-1440.png'),fullPage:true});}await page.locator('#archive-results [data-record]').click();await page.locator('#source-view .sample').waitFor();if(evidence){await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(evidence,'archive-body-1440.png'),fullPage:true});}await check('owner archive search opens indexed body with stable record provenance',async()=>{assert.ok((await page.locator('#source-view .sample').textContent()).startsWith('Archive source evidence café 世界 💠.'));assert.match(await page.locator('#source-view').textContent(),/ordinal=1/);});let archived=await collect('Archive source evidence café 世界 💠.');await check('archive passage collects stable identity and real body',async()=>{assert.equal(archived.format,'archive');assert.equal(archived.anchor.source,'codex');assert.equal(archived.anchor.external_id,'stable-conversation');assert.equal(archived.anchor.ordinal,1);assert.equal(archived.text,'Archive source evidence café 世界 💠.');});
  // Intentional fixture-only changes prove retained evidence survives changed/missing originals.
  fs.writeFileSync(path.join(a,'notes','first.md'),'Changed source record.\n');fs.unlinkSync(path.join(b,'notes','second.md'));expectedSources=treeHashes();await page.reload();await page.locator('.working-excerpt').first().waitFor();await check('changed and missing source observations preserve historical passages',async()=>{const w=await work();assert.equal(w.excerpts.find(x=>x.id===first.id).verification.status,'changed');assert.equal(w.excerpts.find(x=>x.id===other.id).verification.status,'unavailable');assert.equal(w.excerpts.find(x=>x.id===first.id).text,quote);assert.equal(w.excerpts.find(x=>x.id===other.id).text,second);});
  await page.locator('#compile-work').click();await page.locator('#packet-view pre').waitFor();await check('packet exposes changed/missing sources while keeping saved evidence usable',async()=>{const p=await page.locator('#packet-view pre').textContent();assert.ok(p.includes(quote));assert.ok(p.includes(second));assert.ok(p.includes('Current source observation: changed'));assert.ok(p.includes('Current source observation: unavailable'));});
  await page.locator(`[data-reopen="${first.id}"]`).click();await page.locator('#source-view .sample').waitFor();await check('reopen reads changed source without replacing retained quote',async()=>{assert.equal(await page.locator('#source-view .sample').textContent(),'Changed source record.\n');assert.equal((await work()).excerpts.find(x=>x.id===first.id).text,quote);assert.match(await page.locator('#work-status').textContent(),/source has changed/);});
  await page.locator('#work-file').setInputFiles({name:'history.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(historical))});await page.waitForFunction(()=>document.querySelectorAll('.working-excerpt').length===2);await check('historical import keeps Unicode/notes and distinguishes changed/missing verification',async()=>{const w=await work();assert.equal(w.excerpts[0].text,quote);assert.equal(w.excerpts[0].note,note);assert.equal(w.excerpts[0].verification.status,'changed');assert.equal(w.excerpts[1].verification.status,'unavailable');});
  // Reject a collection whose displayed source changed after reading.
  await choose('alpha');await section('first');const staleText=await page.locator('#source-view .sample').textContent();await selectText(staleText.replace(/\n$/,''));const beforeStale=await work();fs.writeFileSync(path.join(a,'notes','first.md'),'Newer source after displayed preview.\n');expectedSources=treeHashes();await page.locator('#collect-selection').click();await page.waitForFunction(()=>document.getElementById('work-status').textContent.includes('Displayed source sample changed'));await check('stale displayed source cannot be collected as newly verified evidence',async()=>{assert.equal((await work()).excerpts.length,beforeStale.excerpts.length);});
  const beforeBadImport=await work();await page.locator('#work-file').setInputFiles({name:'broken.json',mimeType:'application/json',buffer:Buffer.from('{broken JSON')});await page.waitForFunction(()=>document.getElementById('work-status').classList.contains('work-error'));await check('malformed tray import preserves all existing evidence and annotations',async()=>{const now=await work();assert.deepEqual(now.excerpts.map(x=>[x.text,x.note]),beforeBadImport.excerpts.map(x=>[x.text,x.note]));assert.equal(now.revision,beforeBadImport.revision);});
  const secondPage=await ctx.newPage();await secondPage.goto(url);await secondPage.locator('[data-note]').first().waitFor();await secondPage.locator('#work-title').fill('Other-window winning title');const otherSave=secondPage.waitForResponse(r=>r.url().includes('/api/workbench/save'));await secondPage.locator('#save-work').click();assert.equal((await otherSave).status(),200);await page.locator('#work-title').fill('Stale title must not overwrite');const conflict=page.waitForResponse(r=>r.url().includes('/api/workbench/save'));await page.locator('#save-work').click();await check('another-window workbench conflict preserves the winning task and retained source bytes',async()=>{assert.equal((await conflict).status(),409);assert.equal((await work()).title,'Other-window winning title');assert.equal(await page.locator('#work-title').inputValue(),'Stale title must not overwrite');});await secondPage.close();await page.reload();await page.locator('.working-excerpt').first().waitFor();await choose('alpha');await section('first');
  for(const width of [1440,390])for(const theme of ['atlas','circuit','relay']){await page.setViewportSize({width,height:1000});await page.locator('#theme').selectOption(theme);await check(`${theme} theme ${width}px preserves route and prevents page/control overflow`,async()=>{assert.equal(await page.locator('#detail h2').textContent(),'A Laboratory Archive');const o=await page.evaluate(()=>({page:document.documentElement.scrollWidth-document.documentElement.clientWidth,panes:[...document.querySelectorAll('main>.estate,main>.folio,main>.workbench')].map(e=>({tag:e.className,overflow:e.scrollWidth-e.clientWidth}))}));assert.ok(o.page<=1,JSON.stringify(o));assert.ok(o.panes.every(x=>x.overflow<=1),JSON.stringify(o));});if(evidence){fs.mkdirSync(evidence,{recursive:true});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(evidence,`${theme}-${width}.png`),fullPage:true});}}
  await check('all workflows leave source bytes and catalog untouched apart from declared fixture mutations',async()=>{assert.deepEqual(treeHashes(),expectedSources);assert.deepEqual(fs.readFileSync(catalog),catalogBefore);});await check('no unhandled runtime exception or nonlocal network request',async()=>{assert.deepEqual(errors,[]);assert.ok(requests.every(r=>r.url.startsWith(url)));assert.ok(consoleErrors.every(v=>/status of 409 \(Conflict\)/.test(v)),JSON.stringify(consoleErrors));});
  const result={passed,failures,errors,consoleErrors,requestCount:requests.length};if(evidence)fs.writeFileSync(path.join(evidence,'results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));if(failures.length)process.exitCode=1;
 }finally{if(browser)await browser.close();server.kill();await new Promise(r=>server.exitCode!==null||server.signalCode!==null?r():server.once('exit',r));const resolved=path.resolve(root);assert.ok(path.dirname(resolved)===path.resolve(os.tmpdir())&&path.basename(resolved).startsWith('giles-workflows-'));fs.rmSync(resolved,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1});
