'use strict';
// Independent browser regressions for defects found during candidate review.
// This file creates only an isolated temporary catalog/source/server and removes it.
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),cp=require('node:child_process');
let playwright;try{playwright=require(process.env.PLAYWRIGHT_MODULE||'playwright');}catch{playwright=require('C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');}
const chrome=process.env.CHROMIUM_EXECUTABLE||'C:/Users/user/AppData/Local/ms-playwright/chromium-1187/chrome-win/chrome.exe';
const app=path.resolve(__dirname,'../scripts/giles.py');
(async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'giles-independent-')),source=path.join(root,'source'),catalog=path.join(root,'catalog.json');
 fs.mkdirSync(source);fs.mkdirSync(path.join(source,'v1.0'));fs.writeFileSync(path.join(source,'v1.0','README.md'),'Versioned archive entry.\n');fs.writeFileSync(path.join(source,'INDEX.md'),'Source index.\n');
 const alternate=path.join(root,'alternate');fs.mkdirSync(alternate);fs.writeFileSync(path.join(alternate,'INDEX.md'),'Corrected source revision.\n');
 const sourceBefore=[fs.readFileSync(path.join(source,'INDEX.md')),fs.readFileSync(path.join(source,'v1.0','README.md'))];
 const stores=Array.from({length:60},(_,i)=>({id:`store-${String(i).padStart(2,'0')}`,name:`Archive ${String(i).padStart(2,'0')}`,location:source,topics:[i===59?'rare':'ordinary'],favorite:i===59}));
 stores.push({id:'alpha',name:'Alpha Archive',summary:'Original source description',location:source,entrypoint:'v1.0',sections:[{id:'selected',title:'Selected Section',path:'INDEX.md'}]},{id:'beta',name:'Beta Archive',location:source,entrypoint:'INDEX.md'});
 fs.writeFileSync(catalog,JSON.stringify({schema:'giles-knowledge-catalog/v1',revision:0,stores}));
 const server=cp.spawn(process.env.PYTHON||'python',['-B','-X','utf8',app,'--catalog',catalog,'serve','--port','0','--no-browser']);let browser,serverError='',checks=0;
 const checked=(name,fn)=>{fn();checks++;console.log('PASS '+name);};
 server.stderr.on('data',d=>serverError+=d.toString());
 try{
  const url=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Isolated server did not start: '+serverError)),10000);server.stdout.on('data',d=>{const m=d.toString().match(/http:\/\/127\.0\.0\.1:\d+\//);if(m){clearTimeout(timer);resolve(m[0]);}});server.on('error',e=>{clearTimeout(timer);reject(e);});server.on('exit',code=>{clearTimeout(timer);reject(new Error('Server exited '+code+': '+serverError));});});
  browser=await playwright.chromium.launch({headless:true,executablePath:chrome});const ctx=await browser.newContext({permissions:['clipboard-read','clipboard-write'],viewport:{width:1440,height:1040}}),page=await ctx.newPage(),errors=[],requests=[];
  page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
  await page.goto(url);await page.waitForFunction(()=>document.querySelectorAll('#stores .spine').length===62);
  const visibleCount=await page.locator('#stores .spine').count();checked('all registered stores are visible beyond former 50-store cutoff',()=>assert.equal(visibleCount,62));
  await page.getByRole('button',{name:'rare',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('#stores .spine').length===1);const rareID=await page.locator('#stores .spine').getAttribute('data-id');checked('rare topic after position 50 survives filtering',()=>assert.equal(rareID,'store-59'));
  await page.locator('#clear').click();await page.waitForFunction(()=>document.querySelectorAll('#stores .spine').length===62);await page.locator('#favorites').check();await page.waitForFunction(()=>document.querySelectorAll('#stores .spine').length===1);const favoriteID=await page.locator('#stores .spine').getAttribute('data-id');checked('favorite after position 50 survives filtering',()=>assert.equal(favoriteID,'store-59'));await page.locator('#clear').click();await page.locator('[data-id=alpha]').waitFor();await page.locator('[data-id=alpha]').click();
  await page.locator('[data-section=selected]').click();await page.locator('#edit').click();await page.getByRole('button',{name:'Remove entry point',exact:true}).click();await page.getByRole('button',{name:'Save record',exact:true}).click();await page.locator('#editor').waitFor({state:'hidden'});await page.locator('#copy-brief').click();await page.locator('#brief').waitFor();await page.waitForFunction(()=>document.getElementById('notice').textContent==='Retrieval brief copied.');const overview=await page.locator('#brief').inputValue();checked('removing selected section resets retrieval route to store overview',()=>{assert.match(overview,/^Look in Alpha Archive\./);assert.ok(!overview.includes('Selected Section'));assert.match(overview,/v1\.0/);});
  await page.locator('#read-entry').click();await page.waitForFunction(()=>document.getElementById('source-view').textContent.includes('Browsing: v1.0'));await page.locator('[data-path="v1.0/README.md"]').click();await page.locator('.sample').waitFor();const sample=await page.locator('.sample').textContent();checked('dotted folder entrypoint routes through actual filesystem kind',()=>assert.equal(sample,'Versioned archive entry.\n'));
  async function holdBrief(){let release,seen;const held=new Promise(r=>release=r),started=new Promise(r=>seen=r);const handler=async route=>{const response=await route.fetch();seen();await held;await route.fulfill({response});};await page.route('**/api/brief?*',handler);await page.locator('#copy-brief').click();await started;return async()=>{const response=page.waitForResponse(r=>r.url().includes('/api/brief?'));release();await (await response).finished();await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await page.unroute('**/api/brief?*',handler);};}
  await page.evaluate(()=>navigator.clipboard.writeText('UNCHANGED CLIPBOARD'));const releaseSelection=await holdBrief();await page.locator('[data-id=beta]').click();await releaseSelection();const selectedFolio=await page.locator('#detail h2').textContent(),lateBriefCount=await page.locator('#brief').count(),lateClipboard=await page.evaluate(()=>navigator.clipboard.readText());checked('late retrieval response cannot populate another selected folio',()=>{assert.equal(selectedFolio,'Beta Archive');assert.equal(lateBriefCount,0);assert.equal(lateClipboard,'UNCHANGED CLIPBOARD');});
  const token=await page.locator('meta[name=giles-token]').getAttribute('content');const getDoc=async()=>await (await ctx.request.get(url+'api/catalog')).json();const save=async doc=>ctx.request.post(url+'api/save',{headers:{'X-Giles-Token':token},data:{catalog:doc,expected_revision:doc.revision}});
  let doc=await getDoc();doc.stores.push({id:'gamma',name:'Gamma Archive',location:source});assert.equal((await save(doc)).status(),200);await page.locator('#query').fill('Gamma');await page.locator('[data-id=gamma]').waitFor();await page.waitForFunction(()=>document.querySelector('#detail h2')?.textContent==='Gamma Archive');const newFolio=await page.locator('#detail h2').textContent(),newRevision=await page.locator('#revision').textContent();checked('another-window addition yields matching shelf and folio snapshot',()=>{assert.equal(newFolio,'Gamma Archive');assert.match(newRevision,/63 registered stores/);});
  await page.locator('#clear').click();await page.locator('[data-id=alpha]').click();await page.locator('#read-entry').click();await page.locator('[data-path=\"v1.0/README.md\"]').waitFor();await page.locator('[data-path=\"v1.0/README.md\"]').click();await page.locator('.sample').waitFor();await page.evaluate(()=>navigator.clipboard.writeText('REVISION GUARD'));const releaseRevision=await holdBrief();doc=await getDoc();Object.assign(doc.stores.find(s=>s.id==='alpha'),{summary:'Current corrected source description',location:alternate,entrypoint:'INDEX.md'});assert.equal((await save(doc)).status(),200);await page.locator('#query').fill('Alpha');await page.waitForFunction(()=>document.querySelector('#detail .summary')?.textContent==='Current corrected source description');await releaseRevision();const revisionBriefCount=await page.locator('#brief').count(),revisionClipboard=await page.evaluate(()=>navigator.clipboard.readText());checked('late brief cannot restore content from before a catalog revision',()=>{assert.equal(revisionBriefCount,0);assert.equal(revisionClipboard,'REVISION GUARD');});assert.equal(await page.locator('.sample').count(),0);await page.locator('#read-entry').click();await page.locator('.sample').waitFor();const revisedSample=await page.locator('.sample').textContent();checked('snapshot revision clears old source sample and reads the corrected source',()=>assert.equal(revisedSample,'Corrected source revision.\n'));
  let rejected=false;
  for(let i=0;i<5;i++){
   const before=await getDoc(),incoming={schema:'giles-knowledge-catalog/v1',revision:0,stores:[{id:`large-${i}`,name:`Large archive ${i}`,location:source,sections:Array.from({length:256},(_,j)=>({id:`section-${j}`,title:`Section ${j}`,summary:'X'.repeat(2000)}))}]};
   const r=await ctx.request.post(url+'api/import',{headers:{'X-Giles-Token':token},data:{catalog:incoming,expected_revision:before.revision}});
   if(r.status()===400){assert.deepEqual(await getDoc(),before);rejected=true;break;}assert.equal(r.status(),200);
  }
  checked('aggregate size limit rejects oversized merge atomically before UI becomes uneditable',()=>assert.ok(rejected));doc=await getDoc();assert.ok(Buffer.byteLength(JSON.stringify({catalog:doc,expected_revision:doc.revision}))<2000000);doc.stores.find(s=>s.id==='alpha').favorite=true;assert.equal((await save(doc)).status(),200);
  fs.writeFileSync(catalog,'{malformed JSON');const badPage=await ctx.newPage();badPage.on('pageerror',e=>errors.push(e.message));const homepage=await badPage.goto(url);assert.equal(homepage.status(),200);await badPage.waitForFunction(()=>document.querySelector('#detail h2')?.textContent==='Catalog unavailable');checked('corrupt catalog still loads application recovery state',()=>assert.equal(200,homepage.status()));assert.equal(fs.readFileSync(catalog,'utf8'),'{malformed JSON');
  checked('source bytes are unchanged by all workflows',()=>{assert.deepEqual(fs.readFileSync(path.join(source,'INDEX.md')),sourceBefore[0]);assert.deepEqual(fs.readFileSync(path.join(source,'v1.0','README.md')),sourceBefore[1]);});
  checked('runtime has no unhandled application exception or external request',()=>{assert.deepEqual(errors,[]);assert.ok(requests.every(u=>u.startsWith(url)));});
  console.log(`Independent browser regressions: ${checks} workflows passed.`);
 }finally{
  if(browser)await browser.close();server.kill();await new Promise(resolve=>server.exitCode!==null||server.signalCode!==null?resolve():server.once('exit',resolve));const resolved=path.resolve(root),tempBase=path.resolve(os.tmpdir());assert.ok(resolved.startsWith(tempBase+path.sep)&&path.basename(resolved).startsWith('giles-independent-'),'Cleanup must remain inside the isolated temporary directory');fs.rmSync(resolved,{recursive:true,force:true});
 }
})().catch(e=>{console.error(e);process.exitCode=1});
