"use strict";
const $=id=>document.getElementById(id), token=document.querySelector('meta[name=giles-token]').content;
const state={doc:null,hits:[],selected:'',section:'',topic:'',question:'',browse:null,sample:null,ticket:0,sourceTicket:0,busy:false};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug=s=>s.normalize('NFKD').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||'store';
function notice(message,error=false){$('notice').textContent=message;$('notice').className=error?'error':'';}
async function api(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json','X-Giles-Token':token},body:JSON.stringify(body)}:{});const d=await r.json();if(!r.ok)throw new Error(d.error||'Local request failed');return d;}
function download(name,value,type='text/plain'){const u=URL.createObjectURL(new Blob([value],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function selected(){return state.doc?.stores.find(s=>s.id===state.selected);}
function clearSource(){state.sourceTicket++;state.browse=null;state.sample=null;}
async function mutate(work){if(state.busy)throw new Error('A catalog save is already in progress.');state.busy=true;document.querySelectorAll('button.primary').forEach(b=>b.disabled=true);try{state.doc=await work();state.ticket++;clearSource();await runSearch();notice('Catalog saved. Source stores were not changed.');return true;}catch(e){notice(e.message,true);throw e;}finally{state.busy=false;document.querySelectorAll('button.primary').forEach(b=>b.disabled=false);}}
async function saveDoc(doc){return mutate(()=>api('/api/save',{catalog:doc,expected_revision:state.doc.revision}));}
async function reload(){try{state.doc=await api('/api/catalog');clearSource();await runSearch();notice('Catalog reloaded.');}catch(e){notice(e.message,true);$('detail').innerHTML='<h2>Catalog unavailable</h2><p>Preserve the current file; check the startup guide or restore an exported copy.</p>';}}
function renderTopics(){const topics=[...new Set(state.doc.stores.flatMap(s=>s.topics))].sort();$('topics').innerHTML=[['','All knowledge'],...topics.map(t=>[t,t])].map(([value,label])=>`<button class="topic ${state.topic===value?'active':''}" data-topic="${esc(value)}">${esc(label)}</button>`).join('');$('topics').querySelectorAll('button').forEach(b=>b.onclick=()=>{state.topic=b.dataset.topic;runSearch().catch(e=>notice(e.message,true));});}
async function runSearch(){const ticket=++state.ticket;const result=await api('/api/search?q='+encodeURIComponent($('query').value));if(ticket!==state.ticket)return;if(state.doc?.revision!==result.catalog.revision)clearSource();state.doc=result.catalog;state.hits=result.hits.filter(h=>(!state.topic||h.store.topics.includes(state.topic))&&(!$('lifecycle').value||h.store.lifecycle===$('lifecycle').value)&&(!$('favorites').checked||h.store.favorite));if(!state.hits.some(h=>h.store.id===state.selected)){state.selected=state.hits[0]?.store.id||'';state.section='';clearSource();}renderTopics();renderShelf();renderDetail();$('revision').textContent=`Revision ${state.doc.revision} · ${state.doc.stores.length} registered stores`;}
function choose(id){state.selected=id;state.section='';clearSource();renderShelf();renderDetail();if(innerWidth<761)$('detail').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}
function renderShelf(){ $('count').textContent=`${state.hits.length} visible`;if(!state.hits.length){$('stores').innerHTML=`<div class="empty"><h3>${state.doc.stores.length?'No matching stores':'An empty shelf is a beginning.'}</h3><p>${state.doc.stores.length?'Try another remembered fragment, or clear your filters.':'Register a store you want to remember. Keep its content where it already lives.'}</p></div>`;return;}$('stores').innerHTML=state.hits.map((h,i)=>{const s=h.store;return `<button class="spine ${s.id===state.selected?'active':''}" data-id="${s.id}" aria-pressed="${s.id===state.selected}"><span class="number">${String(i+1).padStart(2,'0')}</span><span><h4>${s.favorite?'✦ ':''}${esc(s.name)}</h4><p>${esc(s.summary||'A registered knowledge store awaiting a useful description.')}</p>${s.use_when[0]?`<p class="cue">${esc(s.use_when[0])}</p>`:''}<small>${esc(s.kind)} · ${s.sections.length} entry points · ${esc(s.availability?.state||'not checked')}</small></span></button>`;}).join('');$('stores').querySelectorAll('button').forEach(b=>b.onclick=()=>choose(b.dataset.id));}
function renderDetail(){const s=selected();if(s&&state.section&&!s.sections.some(x=>x.id===state.section)){state.section='';clearSource();}if(!s){$('detail').innerHTML='<p class="eyebrow">A ROUTE WAITING TO BE FOUND</p><h2>Make the familiar<br>findable.</h2><p class="summary">Choose a store from the shelf. Its purpose, provenance and useful entry points will open here.</p>';return;}const a=s.availability;const related=state.doc.stores.filter(x=>x.id!==s.id&&x.topics.some(t=>s.topics.includes(t))).slice(0,5);
$('detail').innerHTML=`<p class="eyebrow">THE OPEN FOLIO / ${esc(s.owner||'CUSTODIAN UNRECORDED')}</p><h2>${esc(s.name)}</h2><p class="summary">${esc(s.summary||'Add a description that helps your future self recognize this store.')}</p><div class="meta"><span class="badge">${esc(s.role)}</span><span class="badge">${esc(s.lifecycle)}</span><span class="badge">${esc(s.inspection.replaceAll('_',' '))}</span></div><div class="toolbar"><button id="favorite">${s.favorite?'Unmark store':'Mark for return'}</button><button id="edit">Edit record</button><button id="check">Check location</button></div><h3>Use this when…</h3>${s.use_when.map(x=>`<p class="cue-line">↳ ${esc(x)}</p>`).join('')||'<p class="provenance">Useful situations have not been recorded yet.</p>'}${s.aliases.length?`<p class="provenance rule">Also remembered as: ${esc(s.aliases.join(' · '))}</p>`:''}<div class="rule"><p class="eyebrow">START WITH ONE USEFUL ENTRY POINT</p><button class="entry ${!state.section?'active':''}" data-section=""><strong>Store overview</strong><span>${esc(s.entrypoint||'Registered root')}</span></button>${s.sections.map(x=>`<button class="entry ${state.section===x.id?'active':''}" data-section="${x.id}"><strong>${esc(x.title)}</strong><span>${esc(x.summary||x.path||'Registered root')}</span></button>`).join('')}<div class="toolbar"><button id="read-entry">Read entry point</button><button id="browse">Browse source</button></div><div id="source-view"></div></div><div class="rule"><h3>Hand the thread to Nova</h3><label for="question">What should we investigate here?</label><input id="question" value="${esc(state.question)}" placeholder="Optional: the question you want this source to answer"><div class="toolbar"><button id="copy-brief" class="primary">Prepare & copy retrieval brief</button><button id="download-brief">Download brief</button></div><div id="brief-view"></div></div>${related.length?`<div class="rule"><h3>Nearby on the shelf</h3><p class="provenance">Connected by your recorded topics.</p><div class="toolbar">${related.map(x=>`<button data-related="${x.id}">${esc(x.name)}</button>`).join('')}</div></div>`:''}<div class="rule"><p class="eyebrow">SOURCE & CUSTODY</p><div class="location">${esc(s.location)}</div><p class="availability">${a?`${esc(a.state)} · checked ${esc(a.checked_at)}<br>${esc(a.detail)}`:'Availability has not been checked.'}</p><p class="provenance">${esc(s.provenance||'Description basis has not been recorded.')}</p><div class="toolbar"><button id="copy-location">Copy location</button><button id="remove" class="danger">Remove catalog record</button></div></div>`;
$('favorite').onclick=()=>{const doc=structuredClone(state.doc);doc.stores.find(x=>x.id===s.id).favorite=!s.favorite;saveDoc(doc).catch(()=>{});};$('edit').onclick=()=>openEditor(s);$('check').onclick=()=>mutate(()=>api('/api/check',{id:s.id,expected_revision:state.doc.revision})).catch(()=>{});
$('detail').querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{state.section=b.dataset.section;clearSource();renderDetail();});$('detail').querySelectorAll('[data-related]').forEach(b=>b.onclick=()=>choose(b.dataset.related));
$('question').oninput=e=>state.question=e.target.value;
$('browse').onclick=()=>{const sub=s.sections.find(x=>x.id===state.section);openSource(sub?.path||'');};$('read-entry').onclick=()=>{const sub=s.sections.find(x=>x.id===state.section);const path=sub?sub.path:s.entrypoint;openEntry(path);};
$('copy-brief').onclick=async()=>{try{const sid=state.selected,section=state.section,question=state.question,ticket=state.sourceTicket;const text=await getBrief();if(state.selected!==sid||state.section!==section||state.question!==question||ticket!==state.sourceTicket)return;$('brief-view').innerHTML='<label for="brief">Retrieval brief</label><textarea id="brief" rows="8" readonly></textarea>';$('brief').value=text;await copy(text,'Retrieval brief copied.');}catch(e){notice(e.message,true);}};
$('download-brief').onclick=async()=>{try{const sid=state.selected,section=state.section,question=state.question,ticket=state.sourceTicket;const text=await getBrief();if(state.selected!==sid||state.section!==section||state.question!==question||ticket!==state.sourceTicket)return;download(s.id+'-retrieval-brief.txt',text);notice('Retrieval brief downloaded.');}catch(e){notice(e.message,true);}};
$('copy-location').onclick=()=>copy(s.location,'Source location copied.');$('remove').onclick=()=>{if(confirm(`Remove ${s.name} from this catalog? Its source store will stay where it is.`)){const d=structuredClone(state.doc);d.stores=d.stores.filter(x=>x.id!==s.id);saveDoc(d).catch(()=>{});}};renderSource();}
async function copy(value,message){try{await navigator.clipboard.writeText(value);notice(message);}catch{notice('Clipboard unavailable. Select and copy the displayed brief or location.');}}
function getBrief(){return api('/api/brief?'+new URLSearchParams({id:state.selected,section:state.section,question:state.question})).then(d=>d.text);}
async function openEntry(path){const sid=state.selected;const ticket=++state.sourceTicket;state.sample=null;state.browse=null;try{const data=await api('/api/browse?'+new URLSearchParams({id:sid,path}));if(state.selected!==sid||ticket!==state.sourceTicket)return;if(data.file){const sample=await api('/api/preview?'+new URLSearchParams({id:sid,path}));if(state.selected!==sid||ticket!==state.sourceTicket)return;state.sample=sample;}else state.browse=data;renderSource();}catch(e){if(ticket===state.sourceTicket)notice(e.message,true);}}
async function openSource(path){const sid=state.selected;const ticket=++state.sourceTicket;state.sample=null;try{const data=await api('/api/browse?'+new URLSearchParams({id:sid,path}));if(state.selected!==sid||ticket!==state.sourceTicket)return;state.browse=data;renderSource();}catch(e){if(ticket===state.sourceTicket)notice(e.message,true);}}
async function openSample(path){const sid=state.selected;const ticket=++state.sourceTicket;try{const data=await api('/api/preview?'+new URLSearchParams({id:sid,path}));if(state.selected!==sid||ticket!==state.sourceTicket)return;state.sample=data;renderSource();}catch(e){if(ticket===state.sourceTicket)notice(e.message,true);}}
function renderSource(){const target=$('source-view');if(!target)return;let html='';if(state.browse){const b=state.browse;html=`<div class="location">Browsing: ${esc(b.path||'registered root')}</div>${b.path?'<button id="up">↑ Parent folder</button>':''}<ul class="source-list">${b.entries.map(e=>`<li><button data-path="${esc(e.path)}" data-dir="${e.directory}" ${e.linked?'disabled':''}>${e.directory?'↳ ':''}${esc(e.name)}<span class="meta">${e.linked?'Linked entry — register its direct location':e.directory?'Folder':`${e.bytes} bytes · text preview where supported`}</span></button></li>`).join('')}</ul><p class="provenance">${b.file?'This registered source is a file. Use Read entry point to inspect a supported text sample.':b.entries.length?'Names and metadata only; directory listing is not content reading.':'No visible entries in this folder.'}${b.truncated?' Showing first 200 entries.':''}</p>`;}if(state.sample){html+=`<p class="provenance">Explicit text sample: ${esc(state.sample.path||'registered file')} · ${state.sample.bytes_loaded} bytes${state.sample.truncated?' · truncated at 32 KB':''}</p><pre class="sample">${esc(state.sample.text)}</pre>`;}target.innerHTML=html;if($('up'))$('up').onclick=()=>openSource(state.browse.path.split('/').slice(0,-1).join('/'));target.querySelectorAll('[data-path]').forEach(b=>b.onclick=()=>b.dataset.dir==='true'?openSource(b.dataset.path):openSample(b.dataset.path));}
function sectionFields(s={id:'',title:'',path:'',summary:'',topics:[]}){const block=document.createElement('div');block.className='section-fields';block.dataset.id=s.id;block.innerHTML=`<label>Section name<input data-field="title" value="${esc(s.title)}" required></label><label>Relative source path<input data-field="path" value="${esc(s.path)}"></label><label>Recognition cue<input data-field="summary" value="${esc(s.summary)}"></label><label>Topics, comma separated<input data-field="topics" value="${esc(s.topics.join(', '))}"></label><button type="button">Remove entry point</button>`;block.querySelector('button').onclick=()=>block.remove();$('section-fields').append(block);}
function openEditor(s){const f=$('store-form');f.reset();$('form-error').textContent='';$('section-fields').innerHTML='';$('edit-title').textContent=s?'Edit a knowledge store':'Register a knowledge store';for(const key of ['id','name','location','summary','kind','role','lifecycle','inspection','owner','entrypoint','provenance'])f.elements.namedItem(key).value=s?.[key]??(key==='kind'?'folder':key==='role'||key==='lifecycle'?'unresolved':key==='inspection'?'metadata_only':'');for(const key of ['topics','aliases','use_when'])f.elements.namedItem(key).value=s?.[key]?.join(key==='use_when'?'\n':', ')||'';(s?.sections||[]).forEach(sectionFields);$('editor').showModal();}
$('store-form').onsubmit=async e=>{e.preventDefault();const f=e.target;const d=structuredClone(state.doc);const id=f.elements.id.value||slug(f.elements.name.value)+'-'+crypto.randomUUID().slice(0,6);const old=d.stores.find(s=>s.id===id);const row={...(old||{}),id};for(const key of ['name','location','summary','kind','role','lifecycle','inspection','owner','entrypoint','provenance'])row[key]=f.elements.namedItem(key).value;for(const key of ['topics','aliases','use_when'])row[key]=f.elements.namedItem(key).value.split(key==='use_when'?/\n/:/,/).map(x=>x.trim()).filter(Boolean);row.sections=[...$('section-fields').children].map((b,i)=>{const val=k=>b.querySelector(`[data-field=${k}]`).value;return{id:b.dataset.id||slug(val('title'))+'-'+i,title:val('title'),path:val('path'),summary:val('summary'),topics:val('topics').split(',').map(x=>x.trim()).filter(Boolean)};});row.favorite=old?.favorite||false;if(old)d.stores[d.stores.indexOf(old)]=row;else d.stores.push(row);try{state.selected=id;await saveDoc(d);$('editor').close();}catch(e){$('form-error').textContent=e.message;}};
$('add-section').onclick=()=>sectionFields();$('close-editor').onclick=()=>$('editor').close();$('add').onclick=()=>openEditor();$('reload').onclick=reload;
let debounce;$('query').oninput=()=>{clearTimeout(debounce);debounce=setTimeout(()=>runSearch().catch(e=>notice(e.message,true)),100);};$('lifecycle').onchange=$('favorites').onchange=()=>runSearch().catch(e=>notice(e.message,true));$('clear').onclick=()=>{state.topic='';$('lifecycle').value='';$('favorites').checked=false;$('query').value='';runSearch().catch(e=>notice(e.message,true));};
$('export').onclick=async()=>{try{download('giles-catalog.json',JSON.stringify(await api('/api/export'),null,2)+'\n','application/json');notice('Catalog exported. This contains locators and notes, not source bodies.');}catch(e){notice(e.message,true);}};
$('import').onclick=()=>{$('import-error').textContent='';$('import-file').value='';$('replace-import').checked=false;$('importer').showModal();};$('close-import').onclick=()=>$('importer').close();$('do-import').onclick=async()=>{try{const f=$('import-file').files[0];if(!f)throw new Error('Choose an exported catalog file.');if(f.size>2000000)throw new Error('Catalog file exceeds 2 MB.');const doc=JSON.parse(await f.text());await mutate(()=>api('/api/import',{catalog:doc,expected_revision:state.doc.revision,replace:$('replace-import').checked}));$('importer').close();}catch(e){$('import-error').textContent=e.message;}};
reload();
