"use strict";
const $=id=>document.getElementById(id), token=document.querySelector('meta[name=giles-token]').content;
const state={doc:null,hits:[],selected:'',section:'',topic:'',question:'',browse:null,sample:null,overview:null,route:'',routeMode:'overview',sourceError:'',loading:false,ticket:0,sourceTicket:0,busy:false,view:'map',work:null,anchor:{offset:0,page:0},archive:null,archiveSummary:null,selection:'',workBusy:true};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug=s=>s.normalize('NFKD').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||'store';
function preference(name,value){try{if(value===undefined)return localStorage.getItem('giles-'+name);localStorage.setItem('giles-'+name,value);}catch{}return null;}
function notice(message,error=false){$('notice').textContent=message;$('notice').className=error?'error':'';}
async function api(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json','X-Giles-Token':token},body:JSON.stringify(body)}:{});const d=await r.json();if(!r.ok)throw new Error(d.error||'Local request failed');return d;}
function download(name,value,type='text/plain'){const u=URL.createObjectURL(new Blob([value],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function selected(){return state.doc?.stores.find(s=>s.id===state.selected);}
function clearSource(){state.sourceTicket++;state.browse=null;state.sample=null;state.overview=null;state.sourceError='';state.loading=false;state.selection='';state.archive=null;state.archiveSummary=null;}
function applyTheme(value){const theme=['atlas','circuit','relay'].includes(value)?value:'atlas';document.documentElement.dataset.theme=theme;$('theme').value=theme;preference('theme',theme);renderMap();}
function applyView(value){state.view=value==='list'?'list':'map';document.documentElement.dataset.view=state.view;$('view-map').setAttribute('aria-pressed',state.view==='map');$('view-list').setAttribute('aria-pressed',state.view==='list');preference('view',state.view);}
$('theme').onchange=e=>applyTheme(e.target.value);$('view-map').onclick=()=>applyView('map');$('view-list').onclick=()=>applyView('list');
applyTheme(preference('theme'));applyView(preference('view'));
async function mutate(work){if(state.busy)throw new Error('A catalog save is already in progress.');state.busy=true;document.querySelectorAll('button.primary').forEach(b=>b.disabled=true);try{state.doc=await work();state.ticket++;clearSource();await runSearch();notice('Catalog saved. Source stores were not changed.');return true;}catch(e){notice(e.message,true);throw e;}finally{state.busy=false;document.querySelectorAll('button.primary').forEach(b=>b.disabled=false);}}
async function saveDoc(doc){return mutate(()=>api('/api/save',{catalog:doc,expected_revision:state.doc.revision}));}
async function reload(){try{state.doc=await api('/api/catalog');if(!state.selected)state.selected=preference('selected')||'';clearSource();await runSearch();await loadWorkbench();notice('Choose a collection to inspect its overview.');}catch(e){notice(e.message,true);$('detail').innerHTML='<h2>Catalog unavailable</h2><p>Preserve the current file; check the startup guide or restore an exported copy.</p>';}}
function renderTopics(){const topics=[...new Set(state.doc.stores.flatMap(s=>s.topics))].sort();$('topics').innerHTML=[['','All knowledge'],...topics.map(t=>[t,t])].map(([value,label])=>`<button class="topic ${state.topic===value?'active':''}" data-topic="${esc(value)}" aria-pressed="${state.topic===value}">${esc(label)}</button>`).join('');$('topics').querySelectorAll('button').forEach(b=>b.onclick=()=>{state.topic=b.dataset.topic;runSearch().catch(e=>notice(e.message,true));});}
async function runSearch(){const ticket=++state.ticket;const result=await api('/api/search?q='+encodeURIComponent($('query').value));if(ticket!==state.ticket)return;if(state.doc?.revision!==result.catalog.revision)clearSource();state.doc=result.catalog;state.hits=result.hits.filter(h=>(!state.topic||h.store.topics.includes(state.topic))&&(!$('lifecycle').value||h.store.lifecycle===$('lifecycle').value)&&(!$('favorites').checked||h.store.favorite));if(!state.hits.some(h=>h.store.id===state.selected)){state.selected=state.hits[0]?.store.id||'';state.section='';state.route='';state.routeMode='overview';clearSource();}if(state.section&&!selected()?.sections.some(x=>x.id===state.section)){state.section='';state.route='';state.routeMode='overview';clearSource();}renderTopics();renderShelf();renderMap();renderDetail();$('revision').textContent=`${state.doc.stores.length} stores · catalog revision ${state.doc.revision}`;if(selected()&&!state.overview&&!state.browse&&!state.sample&&!state.loading)loadOverview();}
function choose(id){state.selected=id;state.section='';state.route='';state.routeMode='overview';preference('selected',id);clearSource();renderShelf();renderMap();renderDetail();loadOverview();if(innerWidth<761)$('detail').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}
function renderShelf(){ $('count').textContent=`${state.hits.length} of ${state.doc.stores.length}`;$('results-title').textContent=$('query').value||state.topic?'Matching collections':'Your collections';if(!state.hits.length){$('stores').innerHTML=`<div class="empty"><h3>${state.doc.stores.length?'No matching collections':'Keep your first collection findable.'}</h3><p>${state.doc.stores.length?'Try another remembered fragment, or clear the filters. The estate map keeps the rest in view.':'Register an archive, notebook or reference library that already exists. Its content stays where it is.'}</p></div>`;return;}$('stores').innerHTML=state.hits.map((h,i)=>{const s=h.store;return `<button class="spine ${s.id===state.selected?'active':''}" data-id="${s.id}" aria-pressed="${s.id===state.selected}"><span class="number">${String(i+1).padStart(2,'0')}</span><span><h4>${s.favorite?'✦ ':''}${esc(s.name)}</h4><p>${esc(s.summary||'A knowledge collection awaiting a useful description.')}</p><small>${esc(s.topics.slice(0,3).join(' / ')||s.kind)} · ${s.sections.length} named sections</small>${h.matched_sections.length?`<span class="match-cue">Matched sections: ${esc(s.sections.filter(x=>h.matched_sections.includes(x.id)).map(x=>x.title).join(', '))}</span>`:''}</span></button>`;}).join('');$('stores').querySelectorAll('button').forEach(b=>b.onclick=()=>choose(b.dataset.id));}
function renderMap(){if(!state.doc||!$('estate-map'))return;const all=[...state.doc.stores].sort((a,b)=>a.name.localeCompare(b.name));let nodes=all.slice(0,12);const focus=selected();if(focus&&!nodes.some(s=>s.id===focus.id))nodes=[...nodes.slice(0,11),focus];const n=nodes.length;let links='';const positions=nodes.map((s,i)=>{const angle=-Math.PI/2+i*2*Math.PI/Math.max(n,1);return {x:n===1?50:50+34*Math.cos(angle),y:n===1?50:50+34*Math.sin(angle)};});const ix=nodes.findIndex(s=>s.id===state.selected);if(ix>=0)nodes.forEach((s,i)=>{if(i===ix)return;const shared=s.topics.filter(t=>focus.topics.includes(t));if(!shared.length)return;const a=positions[ix],b=positions[i],circuit=document.documentElement.dataset.theme==='circuit';const d=circuit?`M ${a.x} ${a.y} H ${(a.x+b.x)/2} V ${b.y} H ${b.x}`:`M ${a.x} ${a.y} Q 50 50 ${b.x} ${b.y}`;links+=`<path d="${d}" data-from="${focus.id}" data-to="${s.id}" data-topics="${esc(shared.join(', '))}"><title>${esc(shared.join(', '))}</title></path>`;});const visible=new Set(state.hits.map(h=>h.store.id));$('estate-map').innerHTML=`<svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">${links}</svg><div class="map-center"><span class="eyebrow">KEPT KNOWLEDGE</span><strong>${all.length}</strong><span>registered stores</span></div>${nodes.map((s,i)=>`<button class="map-node ${s.id===state.selected?'active':''} ${visible.has(s.id)?'':'dimmed'}" data-map-id="${s.id}" aria-pressed="${s.id===state.selected}" title="${esc(s.summary||s.name)}"><span class="node-index">${String(all.indexOf(s)+1).padStart(2,'0')}</span><strong>${esc(s.name)}</strong></button>`).join('')}`;$('estate-map').querySelectorAll('[data-map-id]').forEach((b,i)=>{b.style.left=positions[i].x+'%';b.style.top=positions[i].y+'%';b.onclick=()=>{if(!visible.has(b.dataset.mapId)){$('query').value='';state.topic='';$('lifecycle').value='';$('favorites').checked=false;}choose(b.dataset.mapId);runSearch().catch(e=>notice(e.message,true));};});$('map-basis').textContent=`Lines connect the selected store through recorded shared subjects.${all.length>12?` Map shows ${nodes.length} of ${all.length}; every store is available in the list.`:''}`;}
function renderDetail(){const s=selected();if(!s){$('detail').innerHTML='<p class="eyebrow">THE READING DOCK</p><h2>Choose a collection.</h2><p class="summary">Its purpose, actual source overview and useful sections will open here.</p>';return;}const related=state.doc.stores.filter(x=>x.id!==s.id&&x.topics.some(t=>s.topics.includes(t))).slice(0,8);const active=state.routeMode==='overview'?'Store overview':s.sections.find(x=>x.id===state.section)?.title||state.route.split('/').at(-1)||'Store root';
$('detail').innerHTML=`<div class="dock-heading"><div><p class="eyebrow">OPEN COLLECTION</p><h2>${esc(s.name)}</h2></div><button id="favorite" aria-label="${s.favorite?'Unmark':'Mark'} ${esc(s.name)}">${s.favorite?'✦ Marked':'☆ Mark'}</button></div><p class="summary">${esc(s.summary||'The catalog has no description yet. Inspect the source below.')}</p><p class="description-basis">Catalog description · ${esc(s.inspection.replaceAll('_',' '))}</p><div class="section-tabs"><button class="entry ${state.routeMode==='overview'?'active':''}" data-section=""><strong>Store overview</strong></button>${s.sections.map(x=>`<button class="entry ${state.section===x.id&&state.routeMode!=='overview'?'active':''}" data-section="${x.id}" title="${esc(x.summary||x.path)}"><strong>${esc(x.title)}</strong></button>`).join('')}</div><div class="route-bar"><nav id="breadcrumbs" aria-label="Source path"></nav><div class="toolbar"><button id="read-entry">Read entry point</button><button id="browse">Browse source</button></div></div><div id="source-view" aria-live="polite"></div><section class="handoff"><p class="eyebrow">TAKE THIS ROUTE TO NOVA</p><h3>Investigate ${esc(active)}</h3><label for="question">What do you want to find out?</label><input id="question" value="${esc(state.question)}" placeholder="Optional question for this source"><div class="toolbar"><button id="copy-brief" class="primary">Prepare & copy retrieval brief</button><button id="download-brief">Download brief</button></div><div id="brief-view"></div></section>${related.length?`<details class="related"><summary>Connected collections · ${related.length}</summary><p class="provenance">Shared recorded subjects, not verified agreement.</p>${related.map(x=>`<button data-related="${x.id}">${esc(x.name)}<span>${esc(x.topics.filter(t=>s.topics.includes(t)).join(', '))}</span></button>`).join('')}</details>`:''}<details class="custody"><summary>Source, custody & catalog record</summary><div class="location">${esc(s.location)}</div><p class="provenance">${esc(s.provenance||'Description basis has not been recorded.')}</p><div class="meta"><span>${esc(s.owner||'Owner unrecorded')}</span><span>${esc(s.role)}</span><span>${esc(s.lifecycle)}</span></div><p class="availability">${s.availability?`${esc(s.availability.state)} · ${esc(s.availability.checked_at)} · ${esc(s.availability.detail)}`:'No persisted location check.'}</p><div class="toolbar"><button id="edit">Edit record</button><button id="check">Check location</button><button id="copy-location">Copy location</button><button id="remove" class="danger">Remove catalog record</button></div></details>`;
$('favorite').onclick=()=>{const doc=structuredClone(state.doc);doc.stores.find(x=>x.id===s.id).favorite=!s.favorite;saveDoc(doc).catch(()=>{});};$('edit').onclick=()=>openEditor(s);$('check').onclick=()=>mutate(()=>api('/api/check',{id:s.id,expected_revision:state.doc.revision})).catch(()=>{});
$('detail').querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{state.section=b.dataset.section;if(!state.section){state.route='';state.routeMode='overview';clearSource();renderDetail();loadOverview();}else{const sub=s.sections.find(x=>x.id===state.section);openEntry(sub.path);}});$('detail').querySelectorAll('[data-related]').forEach(b=>b.onclick=()=>choose(b.dataset.related));
$('question').oninput=e=>state.question=e.target.value;$('browse').onclick=()=>openSource(state.routeMode==='overview'?'':state.browse?.path??state.route.split('/').slice(0,-1).join('/'));$('read-entry').onclick=()=>{const sub=s.sections.find(x=>x.id===state.section);openEntry(sub?sub.path:s.entrypoint);};
$('copy-brief').onclick=async()=>{try{const snapshot=routeSnapshot();const text=await getBrief();if(!sameRoute(snapshot))return;$('brief-view').innerHTML='<label for="brief">Retrieval brief</label><textarea id="brief" rows="8" readonly></textarea>';$('brief').value=text;await copy(text,'Retrieval brief copied.');}catch(e){notice(e.message,true);}};
$('download-brief').onclick=async()=>{try{const snapshot=routeSnapshot();const text=await getBrief();if(!sameRoute(snapshot))return;download(s.id+'-retrieval-brief.txt',text);notice('Retrieval brief downloaded.');}catch(e){notice(e.message,true);}};
$('copy-location').onclick=()=>copy(s.location,'Source location copied.');$('remove').onclick=()=>{if(confirm(`Remove ${s.name} from this catalog? Its source store will stay where it is.`)){const d=structuredClone(state.doc);d.stores=d.stores.filter(x=>x.id!==s.id);saveDoc(d).catch(()=>{});}};renderSource();}
function routeSnapshot(){return {id:state.selected,section:state.section,path:state.route,revision:state.doc.revision,question:state.question,ticket:state.sourceTicket};}
function sameRoute(x){return x.id===state.selected&&x.section===state.section&&x.path===state.route&&x.revision===state.doc.revision&&x.question===state.question&&x.ticket===state.sourceTicket;}
async function copy(value,message){try{await navigator.clipboard.writeText(value);notice(message);}catch{notice('Clipboard unavailable. Select and copy the displayed brief or location.');}}
function getBrief(){const a=state.archive;return api('/api/brief?'+new URLSearchParams({id:state.selected,section:state.section,path:state.route,question:state.question,expected_revision:state.doc.revision})).then(d=>d.text+(a?`\nIndexed message: ${a.anchor.source} / ${a.anchor.external_id} / ordinal ${a.anchor.ordinal}; offset ${a.anchor.offset}.\nSnapshot: ${a.snapshot_identity}.\nThis is indexed source content; original recorded path: ${a.recorded_source_path||'not recorded'}.\n`:''));}
function sourceQuery(path=''){return new URLSearchParams({id:state.selected,path,offset:state.anchor.offset||0,page:state.anchor.page||0,expected_revision:state.doc.revision});}
function sameSource(x){return x.id===state.selected&&x.section===state.section&&x.path===state.route&&x.revision===state.doc.revision&&x.ticket===state.sourceTicket;}
async function readRoute(mode,path,anchor={offset:0,page:0}){
clearSource();state.anchor=anchor;state.route=path;state.routeMode=mode;state.loading=true;const snapshot=routeSnapshot();renderDetail();
try{
if(mode==='overview'){const overview=await api('/api/overview?'+sourceQuery());if(!sameSource(snapshot))return;state.overview=overview;}
else{const data=await api('/api/browse?'+sourceQuery(path));if(!sameSource(snapshot))return;
if(path==='rag'||path==='rag/archive-current.sqlite3'){const overview=await api('/api/overview?'+sourceQuery());if(!sameSource(snapshot))return;state.archiveSummary=overview.archive||null;}
if(data.file&&!state.archiveSummary){try{const sample=await api('/api/preview?'+sourceQuery(path));if(!sameSource(snapshot))return;state.sample=sample;}catch(e){if(!sameSource(snapshot))return;state.sourceError=e.message;state.browse=data;}}
else state.browse=data;
}
if(!sameSource(snapshot))return;state.loading=false;renderSource();
}catch(e){if(!sameSource(snapshot))return;state.loading=false;state.sourceError=e.message;state.overview=null;state.browse=null;state.sample=null;renderSource();notice(e.message,true);}}
function loadOverview(){return readRoute('overview','');}function openEntry(path,anchor){return readRoute('source',path,anchor);}function openSource(path){return readRoute('source',path);}function openSample(path){return readRoute('source',path);}
function inventoryMarkup(b){return `<div class="inventory-heading"><h3>${b.file?'Source file':'Inside this location'}</h3><span>${b.entries.filter(e=>e.directory).length} folders · ${b.entries.filter(e=>!e.directory&&!e.linked).length} files${b.truncated?' · first 200':''}</span></div><ul class="source-list">${b.entries.map(e=>`<li><button data-path="${esc(e.path)}" ${e.linked?'disabled':''}><span class="file-kind">${e.linked?'LINK':e.directory?'DIR':'FILE'}</span><strong>${esc(e.name)}</strong><span class="file-meta">${e.linked?'Direct location needed':e.directory?'Open folder':`${e.bytes.toLocaleString()} bytes`}</span></button></li>`).join('')}</ul><p class="provenance">${b.entries.length?'Observed directory inventory; individual file contents have not been read.':'No visible entries at this location.'}${b.truncated?' Limited to the first 200 visible entries.':''}</p>`;}
function sampleMarkup(sample){const notes=(sample.notes||[]).join(' ');let html=`<div class="sample-heading"><h3>${sample.format==='image'?'Source image':'Source contents'}</h3><span>${esc(sample.path||'registered file')} · ${sample.bytes_loaded.toLocaleString()} bytes${sample.truncated?' · more content available':''}</span></div>`;
if(sample.format==='image')html+=`<img class="source-image" src="${esc(sample.media_url)}" alt="${esc(sample.path||'Registered source image')}">`;else html+=`<pre class="sample">${esc(sample.text)}</pre>`;
html+=`${sample.format==='archive'?`<p class="provenance">Indexed source message · a bounded window from the archive's published snapshot.</p><details class="reader-provenance"><summary>Reading limits & exact source provenance</summary><p class="provenance">${esc(notes)}</p></details>`:`<p class="provenance">${esc(notes||'Exact bounded source text. Select a passage to collect it with its source route.')}</p>`}<div class="pagination">${(sample.anchor?.offset||sample.offset||sample.page)>0?'<button id="reader-first">Start of document</button>':''}${sample.next_offset!=null?'<button id="reader-next">Next text chunk →</button>':sample.next_page!=null?'<button id="reader-next">Next PDF pages →</button>':''}${sample.page_count!=null?`<span>Pages ${(sample.page||0)+1}–${Math.min((sample.page||0)+(sample.pages_read||6),sample.page_count)} of ${sample.page_count}</span>`:''}</div><div class="reader-actions"><button id="collect-selection" class="primary">${sample.format==='image'?'Collect image reference':'Collect selected passage'}</button>${sample.format!=='image'?'<button id="collect-sample">Collect this text chunk</button>':''}<span id="selection-state" class="provenance">${sample.format==='image'?'Add your interpretation in the working tray.':'Select text in the reader, then collect it.'}</span></div>`;
if(sample.format==='text'||sample.format==='markdown'||sample.path?.endsWith('.md')){const links=[...sample.text.matchAll(/\[([^\]]+)\]\((?:<([^>]+)>|([^\s)]+))(?:\s+"[^"]*")?\)/g)].slice(0,30);if(links.length)html+=`<div class="source-links" aria-label="Links in this source">${links.map(m=>`<button data-doc-link="${esc(m[2]||m[3])}">${esc(m[1])} ↗</button>`).join('')}</div>`;}
return html;}
function normalizeLink(href){let decoded;try{decoded=decodeURIComponent(href.split('#')[0]);}catch{return null;}const parent=state.route.split('/').slice(0,-1);for(const part of decoded.replaceAll('\\','/').split('/')){if(!part||part==='.')continue;if(part==='..'){if(!parent.length)return null;parent.pop();}else parent.push(part);}return parent.join('/');}
function renderSource(){const target=$('source-view');if(!target)return;const s=selected();const parts=state.route.split('/').filter(Boolean);$('breadcrumbs').innerHTML=`<button data-crumb="">${esc(s.name)}</button>${parts.map((p,i)=>`<span aria-hidden="true">/</span><button data-crumb="${esc(parts.slice(0,i+1).join('/'))}">${esc(p)}</button>`).join('')}`;$('breadcrumbs').querySelectorAll('button').forEach(b=>b.onclick=()=>b.dataset.crumb===''?loadOverview():openEntry(b.dataset.crumb));let html='';if(state.loading)html='<div class="loading">Reading this source route…</div>';else if(state.sourceError)html=`<div class="source-state error"><h3>This route could not be inspected.</h3><p>${esc(state.sourceError)}</p><p class="location">${esc(s.location)}${state.route?'/'+esc(state.route):''}</p><button id="retry-source">Retry this route</button></div>`;else if(state.overview){const o=state.overview;html=`<div class="overview-title"><h3>Store overview</h3><span>Live source view · ${esc(o.status.replaceAll('_',' '))}</span></div>${s.use_when.length?`<div class="use-cues"><h4>Come here to…</h4>${s.use_when.map(x=>`<p>${esc(x)}</p>`).join('')}</div>`:''}${o.file?`<p class="provenance">${esc(o.file.name)} · ${o.file.bytes.toLocaleString()} bytes · ${esc(o.file.format)} source file</p>`:''}${o.index?`<div class="index-preview"><div class="sample-heading"><h3>From the source index</h3><span>${esc(o.index.path||'registered file')} · bounded ${o.index.bytes_loaded.toLocaleString()}-byte sample${o.index.truncated?' · truncated':''}</span></div><pre class="sample">${esc(o.index.text)}</pre><button data-path="${esc(o.index.path)}">Inspect this index directly</button></div>`:`<div class="source-state"><p>${esc(o.index_note)}</p>${s.kind==='website'?`<a class="external" href="${esc(s.location)}" target="_blank" rel="noopener noreferrer">Open the source website ↗</a>`:''}</div>`}${o.contents&&!o.contents.file?inventoryMarkup(o.contents):''}<p class="observed">Observed ${esc(new Date(o.observed_at).toLocaleString())}. Reading this view does not change the catalog's inspection claim.</p>`;}else{if(state.browse&&!state.browse.file)html+=inventoryMarkup(state.browse);if(state.sample)html+=sampleMarkup(state.sample);if(state.archive)html+=archiveRecordMarkup(state.archive);}target.innerHTML=html;const sourceText=state.sample?.text??state.overview?.index?.text;const sourcePre=target.querySelector('.sample');if(sourcePre&&sourceText!=null)sourcePre.textContent=sourceText;target.querySelectorAll('[data-path]').forEach(b=>b.onclick=()=>{state.section='';openEntry(b.dataset.path);});if($('retry-source'))$('retry-source').onclick=()=>state.routeMode==='overview'?loadOverview():openEntry(state.route);bindReaderActions();if(state.overview?.archive||state.archiveSummary)renderArchiveSearch(state.overview?.archive||state.archiveSummary);setWorkBusy(state.workBusy);}
function bindReaderActions(){const sample=state.sample;if(sample){if($('reader-first'))$('reader-first').onclick=()=>sample.format==='archive'?openArchiveRecord({...sample.anchor,offset:0}):openEntry(state.route);if($('reader-next'))$('reader-next').onclick=()=>sample.format==='archive'?openArchiveRecord({...sample.anchor,offset:sample.next_offset}):openEntry(state.route,{offset:sample.next_offset??0,page:sample.next_offset!=null?(sample.page||0):sample.next_page});if($('collect-selection'))$('collect-selection').onclick=workAction(()=>collectPassage(sample.format==='image'?'':state.selection));if($('collect-sample'))$('collect-sample').onclick=workAction(()=>collectPassage(sample.text));const pre=$('source-view').querySelector('.sample');if(pre)pre.onmouseup=pre.onkeyup=pre.ontouchend=()=>{const selection=getSelection();state.selection=selection&&pre.contains(selection.anchorNode)&&pre.contains(selection.focusNode)?selection.getRangeAt(0).toString():'';if($('selection-state'))$('selection-state').textContent=state.selection?`${state.selection.length.toLocaleString()} selected characters`:'Select text in the reader, then collect it.';};}
$('source-view').querySelectorAll('[data-doc-link]').forEach(b=>b.onclick=()=>{const href=b.dataset.docLink;if(href.startsWith('#')){const pre=$('source-view').querySelector('.sample'),heading=href.slice(1);let decodedHeading;try{decodedHeading=decodeURIComponent(heading);}catch{notice('This source fragment has invalid URL encoding.',true);return;}const match=[...sample.text.matchAll(/^#{1,6}\s+(.+)$/gm)].find(m=>slug(m[1])===decodedHeading);if(!match){notice('This heading is outside the displayed text chunk, or has no matching Markdown heading.',true);return;}pre.scrollTop=sample.text.slice(0,match.index).split('\n').length*parseFloat(getComputedStyle(pre).lineHeight);notice('Jumped to '+match[1]+'.');return;}if(/^https:\/\//i.test(href)){window.open(href,'_blank','noopener,noreferrer');return;}if(/^[a-z]+:/i.test(href)||href.startsWith('/')){notice('This link points outside the collection. Use its registered source owner.',true);return;}const path=normalizeLink(href);if(path===null){notice('This link leaves the collection. Choose the corresponding registered store.',true);return;}state.section='';openEntry(path);});}
function setWorkBusy(busy){state.workBusy=busy;document.querySelectorAll('#workbench button,#workbench input,#workbench textarea,#collect-selection,#collect-sample').forEach(x=>x.disabled=busy);}
function workAction(action){return async(...args)=>{if(state.workBusy)return;setWorkBusy(true);try{return await action(...args);}catch(e){workNotice(e.message,true);}finally{setWorkBusy(false);}};}
async function loadWorkbench(){setWorkBusy(true);try{state.work=await api('/api/workbench');renderWorkbench();}catch(e){$('work-status').textContent=e.message;$('work-status').classList.add('work-error');}finally{setWorkBusy(false);}}
function renderWorkbench(){$('packet-view').innerHTML='';$('comparison').innerHTML='';const w=state.work;if(!w)return;$('work-title').value=w.title;$('work-goal').value=w.goal;$('work-count').textContent=`${w.excerpts.length} passages · ${new Set(w.excerpts.map(x=>x.store_id+'|'+x.path)).size} sources`;$('tray-count').textContent=w.excerpts.length;$('work-excerpts').innerHTML=w.excerpts.length?w.excerpts.map(x=>`<article class="working-excerpt" data-excerpt="${esc(x.id)}"><h4>${esc(x.store_name)}</h4><p class="anchor">${esc(x.path)} · ${esc(x.format)}${x.format==='pdf'?` · PDF window starts at page ${(x.anchor?.page||0)+1}`:''}${x.anchor?.offset?` · offset ${x.anchor.offset}`:''}</p>${x.text?`<blockquote>${esc(x.text)}</blockquote>`:'<p class="provenance">Collected source image reference</p>'}<p class="provenance">${esc((x.limits||[]).join(' '))}</p>${x.verification?`<p class="provenance">${esc(x.verification.status)} · ${esc(x.verification.detail||'')}</p>`:''}<label>Your annotation · separate from source<textarea data-note="${esc(x.id)}" rows="2">${esc(x.note)}</textarea></label><div class="toolbar"><label class="check"><input type="checkbox" data-compare="${esc(x.id)}"> Compare</label><button data-reopen="${esc(x.id)}">Reopen source</button><button data-remove-excerpt="${esc(x.id)}">Remove from tray</button></div></article>`).join(''):'<div class="empty">Open a source, select a useful passage and collect it here. Your working material is saved separately from the original knowledge store.</div>';
$('work-excerpts').querySelectorAll('[data-remove-excerpt]').forEach(b=>b.onclick=workAction(async()=>{const w=workDraft();w.excerpts=w.excerpts.filter(x=>x.id!==b.dataset.removeExcerpt);try{await saveWorkbench(w);}catch{}}));$('work-excerpts').querySelectorAll('[data-reopen]').forEach(b=>b.onclick=async()=>{const x=w.excerpts.find(x=>x.id===b.dataset.reopen);if(!state.doc.stores.some(s=>s.id===x.store_id)){workNotice('This catalog locator was removed. The retained evidence is still in your tray.',true);return;}choose(x.store_id);state.section='';if(x.format==='archive'){await openArchiveRecord(x.anchor);return;}await openEntry(x.path,x.anchor);if(state.sample&&state.sample.source_fingerprint!==x.source_fingerprint)workNotice('The source has changed since this passage was collected. Its retained snapshot is preserved.',true);});setWorkBusy(state.workBusy);}
function workDraft(){const w=structuredClone(state.work);w.title=$('work-title').value;w.goal=$('work-goal').value;for(const x of w.excerpts){const n=$('work-excerpts').querySelector(`[data-note="${x.id}"]`);if(n)x.note=n.value;}return w;}
function workNotice(message,error=false){$('work-status').textContent=message;$('work-status').classList.toggle('work-error',error);}
async function saveWorkbench(w=workDraft()){try{state.work=await api('/api/workbench/save',{workbench:w,expected_revision:state.doc.revision,expected_workbench_revision:state.work.revision});renderWorkbench();workNotice('Working task and annotations saved.');return true;}catch(e){workNotice(e.message,true);throw e;}}
async function collectPassage(text){try{const sample=state.sample||state.archive;if(!sample)throw Error('Open source contents first.');if(sample.format!=='image'&&!text)throw Error('Select a passage in the source reader.');const snapshot=routeSnapshot();await saveWorkbench();if(!sameSource(snapshot))throw Error('The open source changed. Select a passage in the current reader.');state.work=await api('/api/collect',{id:state.selected,path:state.route,text,note:'',anchor:sample.anchor||state.anchor,sample_sha256:sample.sample_sha256,expected_revision:state.doc.revision,expected_workbench_revision:state.work.revision});renderWorkbench();workNotice('Source material collected with its route and provenance.');notice('Collected in the working tray.');}catch(e){workNotice(e.message,true);notice(e.message,true);}}
$('work-jump').onclick=()=>$('workbench').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});$('save-work').onclick=workAction(()=>saveWorkbench());
$('compare-work').onclick=workAction(()=>{const ids=[...$('work-excerpts').querySelectorAll('[data-compare]:checked')].map(b=>b.dataset.compare);const rows=ids.length?state.work.excerpts.filter(x=>ids.includes(x.id)):state.work.excerpts.slice(-2);if(rows.length!==2){workNotice('Choose two collected sources to compare.',true);return;}$('comparison').innerHTML=`<h3>Compare the evidence</h3><p class="provenance">Two retained source snapshots. Add interpretation in their annotations; this view makes no claim of semantic agreement.</p><div class="compare-columns">${rows.map(x=>`<article><h4>${esc(x.store_name)} / ${esc(x.path)}</h4><pre>${esc(x.text||'Image reference')}</pre></article>`).join('')}</div>`;workNotice('Two source snapshots are displayed side by side.');});
$('compile-work').onclick=workAction(async()=>{try{await saveWorkbench();const d=await api('/api/packet');if(d.catalog_revision!==state.doc.revision||d.workbench_revision!==state.work.revision)throw Error('The task changed in another window. Reload the working tray before compiling again.');$('packet-view').innerHTML='<h3>Knowledge packet</h3><pre class="sample packet-preview"></pre><div class="toolbar"><button id="download-packet">Download Markdown packet</button><button id="copy-packet">Copy packet for Nova</button></div>';$('packet-view').querySelector('pre').textContent=d.markdown;$('download-packet').onclick=()=>download(slug(state.work.title||'knowledge-packet')+'.md',d.markdown,'text/markdown');$('copy-packet').onclick=()=>copy(d.markdown,'Knowledge packet copied.');workNotice('Compiled your task, quoted source material, annotations and source routes.');}catch(e){workNotice(e.message,true);}});
$('export-work').onclick=workAction(async()=>{try{await saveWorkbench();download('giles-working-tray.json',JSON.stringify(await api('/api/workbench/export'),null,2)+'\n','application/json');workNotice('Working tray exported.');}catch(e){workNotice(e.message,true);}});$('import-work').onclick=()=>$('work-file').click();$('work-file').onchange=workAction(async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>500000)throw Error('Working tray exceeds 500 KB.');state.work=await api('/api/workbench/import',{workbench:JSON.parse(await file.text()),expected_revision:state.doc.revision,expected_workbench_revision:state.work.revision});renderWorkbench();workNotice('Working tray imported; current source verification is shown separately.');}catch(e){workNotice(e.message,true);}finally{e.target.value='';}});
function renderArchiveSearch(info){let searchTicket=0;const host=document.createElement('section');host.className='archive-reader';host.innerHTML=`<h3>Search the archived knowledge</h3><p class="provenance">${info.document_count} indexed documents · ${info.chunk_count} messages · published ${esc(info.source_modified_at||'date unrecorded')}</p><label for="archive-query">Find within recorded content</label><div class="toolbar"><input id="archive-query" placeholder="Words from a past discussion"><button id="archive-find">Retrieve messages</button></div><div id="archive-results"><p class="provenance">Retrieving published records…</p></div>`;$('source-view').prepend(host);$('archive-query').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();$('archive-find').click();}};$('archive-find').onclick=async()=>{const snapshot=routeSnapshot(),ticket=++searchTicket;$('archive-results').innerHTML='<p class="provenance">Retrieving published records…</p>';try{const d=await api('/api/archive/search?'+new URLSearchParams({id:state.selected,q:$('archive-query').value,snapshot:info.snapshot,expected_revision:state.doc.revision}));if(!sameSource(snapshot)||ticket!==searchTicket)return;$('archive-results').innerHTML=d.hits.map((h,i)=>`<button data-record="${i}"><strong>${esc(h.title)}</strong><span>${esc(h.role)} · ${esc(h.created_at||'date unrecorded')}</span><p>${esc(h.snippet)}</p></button>`).join('')||'<p class="provenance">No literal matches in this indexed snapshot.</p>';$('archive-results').querySelectorAll('[data-record]').forEach(b=>b.onclick=()=>openArchiveRecord({...d.hits[Number(b.dataset.record)].locator,snapshot:d.snapshot,offset:0}));}catch(e){if(!sameSource(snapshot)||ticket!==searchTicket)return;$('archive-results').innerHTML=`<p class="error">${esc(e.message)} Reload the store overview to use the current published snapshot.</p>`;notice(e.message,true);}};$('archive-find').click();}
async function openArchiveRecord(anchor){clearSource();state.route='rag/archive-current.sqlite3';state.routeMode='source';state.anchor=anchor;state.loading=true;const snapshot=routeSnapshot();renderDetail();try{const d=await api('/api/archive/record?'+new URLSearchParams({id:state.selected,...anchor,expected_revision:state.doc.revision}));if(!sameSource(snapshot))return;state.archive=d;state.sample=d;state.loading=false;renderSource();}catch(e){if(!sameSource(snapshot))return;state.loading=false;state.sourceError=e.message;renderSource();}}
function archiveRecordMarkup(d){return `<p class="provenance">Indexed message · ${esc(d.title)} · ${esc(d.role)} · ${esc(d.created_at||'date unrecorded')} · snapshot ${esc(d.snapshot_identity?.slice(0,12)||'')}</p>`;}

function sectionFields(s={id:'',title:'',path:'',summary:'',topics:[]}){const block=document.createElement('div');block.className='section-fields';block.dataset.id=s.id;block.innerHTML=`<label>Section name<input data-field="title" value="${esc(s.title)}" required></label><label>Relative source path<input data-field="path" value="${esc(s.path)}"></label><label>Recognition cue<input data-field="summary" value="${esc(s.summary)}"></label><label>Topics, comma separated<input data-field="topics" value="${esc(s.topics.join(', '))}"></label><button type="button">Remove entry point</button>`;block.querySelector('button').onclick=()=>block.remove();$('section-fields').append(block);}
function openEditor(s){const f=$('store-form');f.reset();$('form-error').textContent='';$('section-fields').innerHTML='';$('edit-title').textContent=s?'Edit a knowledge store':'Register a knowledge store';for(const key of ['id','name','location','summary','kind','role','lifecycle','inspection','owner','entrypoint','provenance'])f.elements.namedItem(key).value=s?.[key]??(key==='kind'?'folder':key==='role'||key==='lifecycle'?'unresolved':key==='inspection'?'metadata_only':'');for(const key of ['topics','aliases','use_when'])f.elements.namedItem(key).value=s?.[key]?.join(key==='use_when'?'\n':', ')||'';(s?.sections||[]).forEach(sectionFields);$('editor').showModal();}
$('store-form').onsubmit=async e=>{e.preventDefault();const f=e.target;const d=structuredClone(state.doc);const id=f.elements.id.value||slug(f.elements.name.value)+'-'+crypto.randomUUID().slice(0,6);const old=d.stores.find(s=>s.id===id);const row={...(old||{}),id};for(const key of ['name','location','summary','kind','role','lifecycle','inspection','owner','entrypoint','provenance'])row[key]=f.elements.namedItem(key).value;for(const key of ['topics','aliases','use_when'])row[key]=f.elements.namedItem(key).value.split(key==='use_when'?/\n/:/,/).map(x=>x.trim()).filter(Boolean);row.sections=[...$('section-fields').children].map((b,i)=>{const val=k=>b.querySelector(`[data-field=${k}]`).value;return{id:b.dataset.id||slug(val('title'))+'-'+i,title:val('title'),path:val('path'),summary:val('summary'),topics:val('topics').split(',').map(x=>x.trim()).filter(Boolean)};});row.favorite=old?.favorite||false;if(old)d.stores[d.stores.indexOf(old)]=row;else d.stores.push(row);try{state.selected=id;await saveDoc(d);$('editor').close();}catch(e){$('form-error').textContent=e.message;}};
$('add-section').onclick=()=>sectionFields();$('close-editor').onclick=()=>$('editor').close();$('add').onclick=()=>openEditor();$('reload').onclick=reload;
let debounce;$('query').oninput=()=>{clearTimeout(debounce);debounce=setTimeout(()=>runSearch().catch(e=>notice(e.message,true)),100);};$('lifecycle').onchange=$('favorites').onchange=()=>runSearch().catch(e=>notice(e.message,true));$('clear').onclick=()=>{state.topic='';$('lifecycle').value='';$('favorites').checked=false;$('query').value='';runSearch().catch(e=>notice(e.message,true));};
$('export').onclick=async()=>{try{download('giles-catalog.json',JSON.stringify(await api('/api/export'),null,2)+'\n','application/json');notice('Catalog exported. This contains locators and notes, not source bodies.');}catch(e){notice(e.message,true);}};
$('import').onclick=()=>{$('import-error').textContent='';$('import-file').value='';$('replace-import').checked=false;$('importer').showModal();};$('close-import').onclick=()=>$('importer').close();$('do-import').onclick=async()=>{try{const f=$('import-file').files[0];if(!f)throw new Error('Choose an exported catalog file.');if(f.size>2000000)throw new Error('Catalog file exceeds 2 MB.');const doc=JSON.parse(await f.text());await mutate(()=>api('/api/import',{catalog:doc,expected_revision:state.doc.revision,replace:$('replace-import').checked}));$('importer').close();}catch(e){$('import-error').textContent=e.message;}};
reload();
